-- cellar27 — guest plan view
--
-- Lets the owner attach one planned_flight to their currently active
-- share_link so guests visiting #/guest/<token> see a read-only,
-- sommelier-narrated walkthrough of tonight's flight (intro + per-pour
-- guidance + food cues). The walkthrough copy is generated by a new
-- request_type 'flight_guest' fired from the owner side; it does NOT
-- consume the share-link AI quota.
--
-- Run via Supabase SQL Editor. Idempotent.

------------------------------------------------------------
-- 1. Allow request_type='flight_guest'.
------------------------------------------------------------

alter table pairing_requests
  drop constraint if exists pairing_requests_request_type_check;

alter table pairing_requests
  add constraint pairing_requests_request_type_check
  check (request_type in ('pairing','flight','drink_now','flight_plan','flight_guest'));

------------------------------------------------------------
-- 2. Attach a planned flight to a share link + carry the walkthrough.
--    guest_view shape:
--      { guest_intro: text,
--        pour_walkthrough: [
--          { bottle_id, what_to_look_for, food_cue, food_when, transition }
--        ] }
------------------------------------------------------------

alter table planned_flights
  add column if not exists shared_via_link_id uuid references share_links(id) on delete set null,
  add column if not exists guest_view jsonb;

-- A given share link surfaces at most one "tonight's flight" — matches
-- the existing single-active-share-link model.
create unique index if not exists planned_flights_shared_link_uidx
  on planned_flights(shared_via_link_id) where shared_via_link_id is not null;

------------------------------------------------------------
-- 3. Anon RPC: given a share token, return the attached planned flight
--    plus the sanitized bottle rows for its picks. No price, no notes,
--    no storage location, no user_id, no source_request_id, no prep,
--    no user_notes — guests get only what they need to enjoy the night.
--    Returns NULL when no plan is attached (so the client can hide the
--    Tonight tab without raising an error).
------------------------------------------------------------

create or replace function cellar27_share_get_planned_flight(p_token text)
returns jsonb
language plpgsql stable security definer set search_path = public as $$
declare
  v_link_id uuid;
  v_owner   uuid;
  v_plan    planned_flights%rowtype;
  v_bottles jsonb;
begin
  select id, owner_user_id into v_link_id, v_owner
    from share_links
   where token       = p_token
     and revoked_at is null
     and expires_at  > now();
  if v_link_id is null then
    raise exception 'link_invalid' using errcode = 'P0001';
  end if;

  select * into v_plan
    from planned_flights
   where shared_via_link_id = v_link_id
     and user_id = v_owner;

  if v_plan.id is null then
    return null;
  end if;

  -- Pull sanitized bottles for each pick. We query bottles directly here
  -- (security definer bypasses RLS) and explicitly project the safe
  -- columns rather than to_jsonb() - drop, so a future column added to
  -- bottles can't accidentally leak.
  select coalesce(jsonb_agg(jsonb_build_object(
           'id',                 b.id,
           'producer',           b.producer,
           'wine_name',          b.wine_name,
           'varietal',           b.varietal,
           'blend_components',   b.blend_components,
           'vintage',            b.vintage,
           'region',             b.region,
           'country',            b.country,
           'style',              b.style,
           'sweetness',          b.sweetness,
           'body',               b.body,
           'drink_window_start', b.drink_window_start,
           'drink_window_end',   b.drink_window_end
         )), '[]'::jsonb)
    into v_bottles
    from bottles b
   where b.user_id = v_owner
     and b.id = any (
       select (elem->>'bottle_id')::uuid
         from jsonb_array_elements(v_plan.picks) elem
     );

  return jsonb_build_object(
    'id',            v_plan.id,
    'title',         v_plan.title,
    'occasion_date', v_plan.occasion_date,
    'theme',         v_plan.theme,
    'guests',        v_plan.guests,
    'narrative',     v_plan.narrative,
    'picks',         v_plan.picks,
    'food',          v_plan.food,
    'guest_view',    v_plan.guest_view,
    'bottles',       v_bottles
  );
end;
$$;

revoke all on function cellar27_share_get_planned_flight(text) from public;
grant execute on function cellar27_share_get_planned_flight(text) to anon, authenticated;
